"use client";

import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, CircleDollarSign, Clock3, Save, Search } from 'lucide-react';
import { AdminNav } from '@/components/admin/AdminNav';
import { useNotification } from '@/context/NotificationContext';
import { SubscriptionPlan } from '@/lib/subscription-plans';
import { cn } from '@/lib/utils';

interface Billing { plan_id: string | null; plan_name: string; billing_cycle: string; price_amount: number; payment_status: string; trial_started_at?: string; trial_ends_at?: string; last_payment_at?: string; next_payment_at?: string; internal_notes?: string }
interface BillingRow { companyOwnerId: string; email: string; name: string; billing: Billing | null }
const emptyBilling = (): Billing => ({ plan_id: null, plan_name: 'Standard', billing_cycle: 'monthly', price_amount: 0, payment_status: 'unknown' });
const dateValue = (value?: string) => value?.slice(0, 10) || '';
const isoDate = (value: string) => value ? new Date(`${value}T12:00:00Z`).toISOString() : '';
const trialInfo = (end?: string) => {
    if (!end) return { days: null, label: 'Kein Enddatum', tone: 'slate' };
    const milliseconds = new Date(end).getTime() - Date.now();
    const days = Math.ceil(milliseconds / 86_400_000);
    if (days < 0) return { days, label: `Seit ${Math.abs(days)} Tag${Math.abs(days) === 1 ? '' : 'en'} abgelaufen`, tone: 'rose' };
    if (days === 0) return { days, label: 'Läuft heute ab', tone: 'amber' };
    return { days, label: `Noch ${days} Tag${days === 1 ? '' : 'e'}`, tone: days <= 3 ? 'amber' : 'emerald' };
};

export default function BillingPage() {
    const [rows, setRows] = useState<BillingRow[]>([]);
    const [plans, setPlans] = useState<SubscriptionPlan[]>([]);
    const [saving, setSaving] = useState('');
    const [search, setSearch] = useState('');
    const [filter, setFilter] = useState('all');
    const [expanded, setExpanded] = useState('');
    const { showToast, showConfirm } = useNotification();
    const load = async () => { try { const [billingResponse, plansResponse] = await Promise.all([fetch('/api/admin/control-center?section=billing', { cache: 'no-store' }), fetch('/api/admin/plans', { cache: 'no-store' })]); const billingPayload = await billingResponse.json(); const plansPayload = await plansResponse.json(); if (!billingResponse.ok) throw new Error(billingPayload.message); if (!plansResponse.ok) throw new Error(plansPayload.message); setRows(billingPayload); setPlans(plansPayload); } catch (error) { showToast(error instanceof Error ? error.message : 'Abrechnung konnte nicht geladen werden.', 'error'); } };
    useEffect(() => { void load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
    const update = (id: string, field: keyof Billing, value: string | number | null) => setRows(current => current.map(row => row.companyOwnerId === id ? { ...row, billing: { ...emptyBilling(), ...row.billing, [field]: value } } : row));
    const choosePlan = (row: BillingRow, planId: string) => { const current = { ...emptyBilling(), ...row.billing }; const plan = plans.find(item => item.id === planId); if (!plan) { update(row.companyOwnerId, 'plan_id', null); return; } const suggestedPrice = current.billing_cycle === 'yearly' ? Number(plan.yearly_price) : Number(plan.monthly_price); setRows(items => items.map(item => item.companyOwnerId === row.companyOwnerId ? { ...item, billing: { ...current, plan_id: plan.id, plan_name: plan.name, price_amount: suggestedPrice } } : item)); };
    const chooseCycle = (row: BillingRow, cycle: string) => { const current = { ...emptyBilling(), ...row.billing }; const plan = plans.find(item => item.id === current.plan_id); const suggestedPrice = plan && cycle !== 'manual' && cycle !== 'free' ? Number(cycle === 'yearly' ? plan.yearly_price : plan.monthly_price) : current.price_amount; setRows(items => items.map(item => item.companyOwnerId === row.companyOwnerId ? { ...item, billing: { ...current, billing_cycle: cycle, price_amount: cycle === 'free' ? 0 : suggestedPrice } } : item)); };
    const startTrial = (row: BillingRow) => { const billing = { ...emptyBilling(), ...row.billing }; const plan = plans.find(item => item.id === billing.plan_id); const now = new Date(); const end = new Date(now); end.setDate(end.getDate() + (plan?.trial_days ?? 14)); setRows(items => items.map(item => item.companyOwnerId === row.companyOwnerId ? { ...item, billing: { ...billing, payment_status: 'trial', trial_started_at: now.toISOString(), trial_ends_at: end.toISOString() } } : item)); };
    const applyTrialAction = async (row: BillingRow, action: 'extend' | 'end' | 'paid', days = 0, confirmed = false) => {
        if (action === 'end' && !confirmed) {
            showConfirm({ title: 'Testphase beenden und Nutzer sperren?', message: `Die laufende Testphase von ${row.name} wird beendet. Der Nutzer wird sofort gesperrt und aktive Sitzungen werden abgemeldet.`, confirmLabel: 'Beenden & sperren', cancelLabel: 'Abbrechen', variant: 'danger', onConfirm: () => { void applyTrialAction(row, 'end', 0, true); } });
            return;
        }
        if (action === 'end' && confirmed) {
            setSaving(row.companyOwnerId);
            try {
                const response = await fetch('/api/admin/control-center', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ companyOwnerId: row.companyOwnerId, suspended: true, reason: 'Testphase beendet' }) });
                const payload = await response.json().catch(() => ({}));
                if (!response.ok) throw new Error(payload.message || `Sperre fehlgeschlagen (HTTP ${response.status})`);
                showToast('Testphase beendet – Nutzer wurde gesperrt.', 'success');
                await load();
            } catch (error) { showToast(error instanceof Error ? error.message : 'Nutzer konnte nicht gesperrt werden.', 'error'); }
            finally { setSaving(''); }
            return;
        }
        const billing = { ...emptyBilling(), ...row.billing };
        if (!billing.plan_id) return showToast('Bitte zuerst ein Paket zuweisen.', 'error');
        const now = new Date();
        let next = { ...billing };
        if (action === 'extend') { const currentEnd = billing.trial_ends_at ? new Date(billing.trial_ends_at) : now; const base = currentEnd.getTime() > now.getTime() ? currentEnd : now; base.setUTCDate(base.getUTCDate() + days); next = { ...billing, payment_status: 'trial', trial_started_at: billing.trial_started_at || now.toISOString(), trial_ends_at: base.toISOString() }; }
        if (action === 'end') next = { ...billing, payment_status: 'open', trial_ends_at: now.toISOString() };
        if (action === 'paid') next = { ...billing, payment_status: 'paid', last_payment_at: now.toISOString() };
        setSaving(row.companyOwnerId);
        try { const body = { action: 'billing_update', companyOwnerId: row.companyOwnerId, planId: next.plan_id, planName: next.plan_name, billingCycle: next.billing_cycle, priceAmount: Number(next.price_amount), paymentStatus: next.payment_status, trialStartedAt: next.trial_started_at || null, trialEndsAt: next.trial_ends_at || null, lastPaymentAt: next.last_payment_at || null, nextPaymentAt: next.next_payment_at || null, internalNotes: next.internal_notes || null }; let response = await fetch('/api/admin/control-center', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (response.status === 404 || response.status === 405) response = await fetch('/api/admin/control-center', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || `Serverfehler (${response.status})`); showToast(action === 'extend' ? `Testphase um ${days} Tage verlängert.` : action === 'end' ? 'Testphase beendet.' : 'Lizenz als bezahlt markiert.', 'success'); await load(); } catch (error) { showToast(error instanceof Error ? error.message : 'Testphase konnte nicht geändert werden.', 'error'); } finally { setSaving(''); }
    };
    const save = async (row: BillingRow) => { setSaving(row.companyOwnerId); const value = row.billing || emptyBilling(); try { const response = await fetch('/api/admin/control-center', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ companyOwnerId: row.companyOwnerId, planId: value.plan_id, planName: value.plan_name, billingCycle: value.billing_cycle, priceAmount: Number(value.price_amount), paymentStatus: value.payment_status, trialStartedAt: value.trial_started_at || null, trialEndsAt: value.trial_ends_at || null, lastPaymentAt: value.last_payment_at || null, nextPaymentAt: value.next_payment_at || null, internalNotes: value.internal_notes || null }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message); showToast(`Abrechnung für ${row.name} gespeichert.`, 'success'); await load(); } catch (error) { showToast(error instanceof Error ? error.message : 'Speichern fehlgeschlagen.', 'error'); } finally { setSaving(''); } };
    const filtered = useMemo(() => rows.filter(row => { const status = row.billing?.payment_status || 'unknown'; return (filter === 'all' || status === filter || (filter === 'critical' && ['overdue','failed'].includes(status))) && `${row.name} ${row.email} ${row.billing?.plan_name || ''}`.toLowerCase().includes(search.toLowerCase()); }), [rows, filter, search]);
    const mrr = rows.filter(row => row.billing?.payment_status === 'paid' && row.billing.billing_cycle !== 'free').reduce((sum, row) => sum + (row.billing?.billing_cycle === 'yearly' ? Number(row.billing.price_amount) / 12 : Number(row.billing?.price_amount || 0)), 0);
    const cards = [{ label: 'Monatlich wiederkehrend', value: `${mrr.toFixed(2)} €`, icon: CircleDollarSign, tone: 'indigo' }, { label: 'Bezahlt', value: rows.filter(row => row.billing?.payment_status === 'paid').length, icon: CheckCircle2, tone: 'emerald' }, { label: 'Kritisch', value: rows.filter(row => ['overdue','failed'].includes(row.billing?.payment_status || '')).length, icon: AlertTriangle, tone: 'rose' }, { label: 'Testphase', value: rows.filter(row => row.billing?.payment_status === 'trial').length, icon: Clock3, tone: 'amber' }];
    const trialRows = rows.filter(row => row.billing?.payment_status === 'trial');

    return <div className="mx-auto max-w-[1500px] space-y-7 p-6 lg:p-10">
        <header><h1 className="text-4xl font-black tracking-tight text-slate-950">Preise & Zahlungen</h1><p className="mt-2 text-sm font-medium text-slate-500">Pakete, individuelle Preise, Zahlungsstatus und interne Abrechnungsdaten.</p></header><AdminNav />
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card => <article key={card.label} className="rounded-3xl border bg-white p-6 shadow-sm"><card.icon className={cn('h-5 w-5', card.tone === 'emerald' ? 'text-emerald-500' : card.tone === 'rose' ? 'text-rose-500' : card.tone === 'amber' ? 'text-amber-500' : 'text-indigo-500')} /><p className="mt-4 text-xs font-black uppercase tracking-widest text-slate-400">{card.label}</p><p className="mt-2 text-3xl font-black text-slate-950">{card.value}</p></article>)}</section>
        {trialRows.length > 0 && <section className="rounded-3xl border border-amber-200 bg-amber-50/60 p-6"><div className="mb-4 flex items-center gap-3"><Clock3 className="h-5 w-5 text-amber-600" /><div><h2 className="font-black text-slate-950">Laufende Testphasen</h2><p className="text-xs font-medium text-slate-500">Überblick und Schnellaktionen – ohne automatische Sperrung.</p></div></div><div className="grid gap-3 xl:grid-cols-2">{trialRows.map(row => { const info = trialInfo(row.billing?.trial_ends_at); return <article key={row.companyOwnerId} className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black text-slate-900">{row.name}</p><p className="text-xs text-slate-500">{row.billing?.plan_name} · bis {row.billing?.trial_ends_at ? new Date(row.billing.trial_ends_at).toLocaleDateString('de-AT') : 'nicht festgelegt'}</p></div><span className={cn('rounded-full px-3 py-1 text-xs font-black', info.tone === 'rose' ? 'bg-rose-100 text-rose-700' : info.tone === 'amber' ? 'bg-amber-100 text-amber-700' : info.tone === 'emerald' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600')}>{info.label}</span></div><div className="mt-4 flex flex-wrap gap-2">{[7,14,30].map(days => <button key={days} onClick={() => applyTrialAction(row, 'extend', days)} disabled={saving === row.companyOwnerId} className="rounded-xl border px-3 py-2 text-xs font-black text-slate-700 disabled:opacity-50">+ {days} Tage</button>)}<button onClick={() => applyTrialAction(row, 'paid')} disabled={saving === row.companyOwnerId} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white disabled:opacity-50">Als bezahlt markieren</button><button onClick={() => applyTrialAction(row, 'end')} disabled={saving === row.companyOwnerId} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-black text-white disabled:opacity-50">Testphase beenden</button></div></article>; })}</div></section>}
        <div className="flex flex-col gap-3 rounded-2xl border bg-white p-3 lg:flex-row lg:justify-between"><div className="flex flex-wrap gap-2">{[['all','Alle'],['paid','Bezahlt'],['open','Offen'],['critical','Kritisch'],['trial','Testphase'],['unknown','Unbekannt']].map(([id,label]) => <button key={id} onClick={() => setFilter(id)} className={cn('rounded-xl px-4 py-2 text-sm font-bold', filter === id ? 'bg-slate-900 text-white' : 'text-slate-500 hover:bg-slate-50')}>{label}</button>)}</div><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Firma, E-Mail oder Tarif…" className="w-80 rounded-xl border py-2.5 pl-10 pr-4 text-sm" /></div></div>
        <div className="space-y-3">{filtered.map(row => { const billing = row.billing || emptyBilling(); return <article key={row.companyOwnerId} className="rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="grid items-center gap-4 p-5 lg:grid-cols-[1.4fr_1fr_1fr_0.8fr_1fr_auto]"><div><p className="font-black text-slate-900">{row.name}</p><p className="text-xs text-slate-500">{row.email}</p></div><select value={billing.plan_id || ''} onChange={event => choosePlan(row, event.target.value)} className="rounded-xl border px-3 py-2 text-sm font-bold"><option value="">{billing.plan_id ? 'Kein Paket' : `Bisher: ${billing.plan_name}`}</option>{plans.filter(plan => plan.is_active || plan.id === billing.plan_id).map(plan => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select><select value={billing.billing_cycle} onChange={event => chooseCycle(row, event.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="monthly">Monatlich</option><option value="yearly">Jährlich</option><option value="manual">Manuell</option><option value="free">Kostenlos</option></select><label className="flex items-center gap-2"><input type="number" min="0" step="0.01" value={billing.price_amount} onChange={event => update(row.companyOwnerId, 'price_amount', Number(event.target.value))} className="w-24 rounded-xl border px-3 py-2 text-sm" /><span className="text-sm font-bold">€</span></label><select value={billing.payment_status} onChange={event => update(row.companyOwnerId, 'payment_status', event.target.value)} className="rounded-xl border px-3 py-2 text-sm font-bold"><option value="unknown">Unbekannt</option><option value="trial">Testphase</option><option value="paid">Bezahlt</option><option value="open">Offen</option><option value="overdue">Überfällig</option><option value="failed">Fehlgeschlagen</option><option value="cancelled">Gekündigt</option><option value="free">Kostenlos</option></select><div className="flex gap-2"><button onClick={() => setExpanded(expanded === row.companyOwnerId ? '' : row.companyOwnerId)} className="rounded-xl border px-3 py-2 text-xs font-black">Details</button><button onClick={() => save(row)} disabled={saving === row.companyOwnerId} className="rounded-xl bg-slate-900 p-3 text-white disabled:opacity-50" title="Speichern"><Save className="h-4 w-4" /></button></div></div>
            {expanded === row.companyOwnerId && <div className="grid gap-4 border-t bg-slate-50/60 p-5 md:grid-cols-3"><label className="text-xs font-black uppercase text-slate-500">Testphase von<input type="date" value={dateValue(billing.trial_started_at)} onChange={event => update(row.companyOwnerId, 'trial_started_at', isoDate(event.target.value))} className="mt-2 block w-full rounded-xl border bg-white px-3 py-2 text-sm font-medium normal-case" /></label><label className="text-xs font-black uppercase text-slate-500">Testphase bis<input type="date" value={dateValue(billing.trial_ends_at)} onChange={event => update(row.companyOwnerId, 'trial_ends_at', isoDate(event.target.value))} className="mt-2 block w-full rounded-xl border bg-white px-3 py-2 text-sm font-medium normal-case" /></label><div className="flex items-end"><button onClick={() => startTrial(row)} disabled={!billing.plan_id} className="w-full rounded-xl border border-indigo-200 bg-indigo-50 px-3 py-2.5 text-sm font-black text-indigo-700 disabled:opacity-40">Testphase ab heute</button></div><label className="text-xs font-black uppercase text-slate-500">Letzte Zahlung<input type="date" value={dateValue(billing.last_payment_at)} onChange={event => update(row.companyOwnerId, 'last_payment_at', isoDate(event.target.value))} className="mt-2 block w-full rounded-xl border bg-white px-3 py-2 text-sm font-medium normal-case" /></label><label className="text-xs font-black uppercase text-slate-500">Nächste Zahlung<input type="date" value={dateValue(billing.next_payment_at)} onChange={event => update(row.companyOwnerId, 'next_payment_at', isoDate(event.target.value))} className="mt-2 block w-full rounded-xl border bg-white px-3 py-2 text-sm font-medium normal-case" /></label><label className="text-xs font-black uppercase text-slate-500 md:col-span-3">Interne Notiz<textarea value={billing.internal_notes || ''} onChange={event => update(row.companyOwnerId, 'internal_notes', event.target.value)} placeholder="Nur für Entwickler sichtbar…" className="mt-2 block min-h-24 w-full rounded-xl border bg-white px-3 py-3 text-sm font-medium normal-case" /></label></div>}
        </article>; })}</div>
    </div>;
}
