import content from '../../../content/public-site.json';
import { LegalPageLayout } from '@/components/public/LegalPageLayout';

export default function PrivacyPage() {
    const company = content.company;
    const privacy = content.privacy;
    return <LegalPageLayout title="Datenschutz" subtitle={`Informationen zur Verarbeitung personenbezogener Daten. Stand: ${privacy.lastUpdated}.`}>
        <article className="border-amber-400/20 bg-amber-400/[0.06]"><h2 className="text-amber-300">Mustertext – vor Veröffentlichung prüfen</h2><p>{content.editingNote}</p></article>
        <article><h2>1. Verantwortlicher</h2><p>{company.legalName}<br />{company.street}, {company.postalCode} {company.city}, {company.country}<br />E-Mail: <a href={`mailto:${company.privacyEmail}`}>{company.privacyEmail}</a><br />Telefon: {company.phone}</p></article>
        <article><h2>2. Welche Daten verarbeitet FlowY?</h2><ul><li>Registrierungs- und Kontaktdaten wie Name, E-Mail-Adresse und Unternehmensdaten</li><li>Anmelde-, Sitzungs- und Sicherheitsdaten, einschließlich technisch gekürzter beziehungsweise gehashter Verbindungsinformationen</li><li>Vom Nutzer eingegebene Geschäfts-, Kunden-, Projekt-, Personal- und Dokumentendaten</li><li>Abrechnungs-, Lizenz- und Nutzungsinformationen</li><li>Supportanfragen und technische Fehlerdaten</li><li>Dateien, die Nutzer in die dafür vorgesehenen Bereiche hochladen</li></ul></article>
        <article><h2>3. Zwecke und Rechtsgrundlagen</h2><p>Die Verarbeitung erfolgt zur Bereitstellung und Absicherung der FlowY-Anwendung, zur Verwaltung von Benutzerkonten und Lizenzen, zur Erfüllung vertraglicher Leistungen, zur Kommunikation sowie zur Fehlerbehebung und Missbrauchsprävention.</p><ul className="mt-4"><li>Vertragserfüllung und vorvertragliche Maßnahmen gemäß Art. 6 Abs. 1 lit. b DSGVO</li><li>Erfüllung rechtlicher Verpflichtungen gemäß Art. 6 Abs. 1 lit. c DSGVO</li><li>Berechtigte Interessen an sicherem und zuverlässigem Betrieb gemäß Art. 6 Abs. 1 lit. f DSGVO</li><li>Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO, soweit sie für einzelne Verarbeitungen eingeholt wird</li></ul></article>
        <article><h2>4. Hosting und technische Dienstleister</h2><p>Die Webanwendung wird über {privacy.hostingProvider} bereitgestellt ({privacy.hostingCountry}). Datenbank, Authentifizierung und Dateispeicher werden über {privacy.backendProvider} betrieben ({privacy.backendCountry}). Soweit erforderlich, werden mit Auftragsverarbeitern Vereinbarungen gemäß Art. 28 DSGVO und geeignete Garantien für internationale Übermittlungen eingesetzt.</p></article>
        <article><h2>5. E-Mail-Versand</h2><p>FlowY ermöglicht den Versand von Geschäftsdokumenten über die vom jeweiligen Unternehmenskonto hinterlegten SMTP-Zugangsdaten. Empfänger-, Absender-, Inhalts- und Anhangsdaten werden dabei an den vom Kunden gewählten E-Mail-Anbieter übertragen. Das jeweilige Unternehmen ist für die rechtmäßige Nutzung seines E-Mail-Dienstes und der Empfängerdaten verantwortlich.</p></article>
        <article><h2>6. Cookies und lokale Speicherung</h2><p>FlowY verwendet technisch notwendige Cookies und Browserspeicher für Anmeldung, Sitzungsverwaltung, Sicherheit und die Funktionsfähigkeit der Anwendung. Nach aktuellem Musterstand werden keine Werbe- oder Analyse-Cookies eingesetzt. Werden künftig optionale Analyse- oder Marketingdienste ergänzt, ist dieser Abschnitt anzupassen und erforderlichenfalls vorher eine Einwilligung einzuholen.</p></article>
        <article><h2>7. Speicherdauer und Kontolöschung</h2><p>Daten werden grundsätzlich nur so lange gespeichert, wie dies für Vertrag, gesetzliche Pflichten, Sicherheit oder die geltend gemachten Zwecke notwendig ist. Bei einer vollständigen Kontolöschung werden aktive Kontodaten entfernt. Zur kontrollierten Wiederherstellung wird ein verschlüsseltes Sicherheitsbackup für 30 Tage aufbewahrt und anschließend automatisiert gelöscht. Gesetzlich erforderliche oder berechtigte administrative Nachweise können davon abweichend gespeichert beziehungsweise anonymisiert werden.</p></article>
        <article><h2>8. Empfänger und Übermittlungen</h2><p>Daten werden nur an eingesetzte technische Dienstleister, vom Kunden ausgewählte Kommunikationsanbieter, gesetzlich berechtigte Stellen oder sonstige Empfänger übermittelt, wenn dafür eine Rechtsgrundlage besteht. Eine Veräußerung personenbezogener Daten findet nicht statt.</p></article>
        <article><h2>9. Ihre Rechte</h2><p>Betroffene Personen haben nach Maßgabe der DSGVO insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung kann mit Wirkung für die Zukunft widerrufen werden. Anfragen können an <a href={`mailto:${company.privacyEmail}`}>{company.privacyEmail}</a> gerichtet werden.</p><p className="mt-4">Darüber hinaus besteht ein Beschwerderecht bei der <a href="https://www.dsb.gv.at/" target="_blank" rel="noreferrer">Österreichischen Datenschutzbehörde</a>, Barichgasse 40–42, 1030 Wien.</p></article>
        <article><h2>10. Datensicherheit und Änderungen</h2><p>FlowY setzt angemessene technische und organisatorische Maßnahmen ein, um Daten vor unbefugtem Zugriff, Verlust und Veränderung zu schützen. Diese Datenschutzerklärung wird angepasst, wenn sich Funktionen, Dienstleister oder rechtliche Anforderungen ändern.</p></article>
    </LegalPageLayout>;
}
