"use client";

import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, ChevronUp, PackagePlus, Save } from 'lucide-react';
import { useNotification } from '@/context/NotificationContext';
import { PLAN_FEATURES, SubscriptionPlan } from '@/lib/subscription-plans';

const blankPlan = (): SubscriptionPlan => ({ id: `draft-${Date.now()}`, slug: '', name: 'Neues Paket', description: '', monthly_price: 0, yearly_price: 0, currency: 'EUR', trial_days: 14, features: [], limits: {}, is_active: true, is_public: false, is_featured: false, sort_order: 40 });

export function PlanManagement() {
    const { showToast } = useNotification();
    const [plans, setPlans] = useState<SubscriptionPlan[]>([]);
    const [open, setOpen] = useState(false);
    const [editing, setEditing] = useState('');
    const [saving, setSaving] = useState('');
    const groups = useMemo(() => Array.from(new Set(PLAN_FEATURES.map(feature => feature.group))), []);
    const load = async () => { try { const response = await fetch('/api/admin/plans', { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message); setPlans(payload); } catch (error) { showToast(error instanceof Error ? error.message : 'Pakete konnten nicht geladen werden.', 'error'); } };
    useEffect(() => { void load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
    const update = (id: string, key: keyof SubscriptionPlan, value: SubscriptionPlan[keyof SubscriptionPlan]) => setPlans(current => current.map(plan => plan.id === id ? { ...plan, [key]: value } : plan));
    const add = () => { const draft = blankPlan(); setPlans(current => [...current, draft]); setEditing(draft.id); setOpen(true); };
    const toggleFeature = (plan: SubscriptionPlan, feature: string) => update(plan.id, 'features', plan.features.includes(feature) ? plan.features.filter(item => item !== feature) : [...plan.features, feature]);
    const save = async (plan: SubscriptionPlan) => { setSaving(plan.id); try { const draft = plan.id.startsWith('draft-'); const response = await fetch('/api/admin/plans', { method: draft ? 'POST' : 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: draft ? undefined : plan.id, slug: plan.slug, name: plan.name, description: plan.description, monthlyPrice: Number(plan.monthly_price), yearlyPrice: Number(plan.yearly_price), currency: plan.currency, trialDays: Number(plan.trial_days), features: plan.features, limits: plan.limits || {}, isActive: plan.is_active, isPublic: plan.is_public, isFeatured: plan.is_featured, sortOrder: Number(plan.sort_order) }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message); showToast(`Paket „${plan.name}“ gespeichert.`, 'success'); setEditing(''); await load(); } catch (error) { showToast(error instanceof Error ? error.message : 'Paket konnte nicht gespeichert werden.', 'error'); } finally { setSaving(''); } };

    return <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
        <button onClick={() => setOpen(value => !value)} className="flex w-full items-center justify-between gap-5 p-6 text-left"><div><div className="flex items-center gap-3"><span className="rounded-xl bg-indigo-50 p-2 text-indigo-600"><PackagePlus className="h-5 w-5" /></span><h2 className="text-xl font-black text-slate-950">Pakete & Leistungen verwalten</h2></div><p className="mt-2 text-sm font-medium text-slate-500">Preise, Sichtbarkeit und enthaltene FlowY-Funktionen zentral pflegen.</p></div>{open ? <ChevronUp className="h-5 w-5 text-slate-400" /> : <ChevronDown className="h-5 w-5 text-slate-400" />}</button>
        {open && <div className="border-t bg-slate-50/60 p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold text-slate-500">Noch ohne Auswirkung auf bestehende Firmen oder Funktionszugriffe.</p><button onClick={add} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-black text-white"><PackagePlus className="h-4 w-4" /> Paket anlegen</button></div><div className="space-y-4">
            {plans.map(plan => <article key={plan.id} className="rounded-2xl border bg-white"><button onClick={() => setEditing(editing === plan.id ? '' : plan.id)} className="grid w-full items-center gap-3 p-5 text-left md:grid-cols-[1.2fr_0.7fr_0.7fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><p className="font-black text-slate-950">{plan.name}</p>{plan.is_featured && <Badge>Empfohlen</Badge>}{!plan.is_active && <Badge>Inaktiv</Badge>}</div><p className="mt-1 text-xs text-slate-500">{plan.features.length} Funktionen · {plan.trial_days} Testtage</p></div><p className="text-sm font-black text-slate-700">{Number(plan.monthly_price).toLocaleString('de-AT', { minimumFractionDigits: 2 })} € / Monat</p><p className="text-sm font-black text-slate-700">{Number(plan.yearly_price).toLocaleString('de-AT', { minimumFractionDigits: 2 })} € / Jahr</p>{editing === plan.id ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</button>
                {editing === plan.id && <div className="space-y-6 border-t p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Input label="Paketname" value={plan.name} onChange={value => update(plan.id, 'name', value)} /><Input label="Interne ID" value={plan.slug} disabled={!plan.id.startsWith('draft-')} onChange={value => update(plan.id, 'slug', value.toLowerCase().replace(/[^a-z0-9-]/g, '-'))} /><Input label="Monatspreis" type="number" value={plan.monthly_price} onChange={value => update(plan.id, 'monthly_price', Number(value))} /><Input label="Jahrespreis" type="number" value={plan.yearly_price} onChange={value => update(plan.id, 'yearly_price', Number(value))} /><Input label="Testtage" type="number" value={plan.trial_days} onChange={value => update(plan.id, 'trial_days', Number(value))} /><Input label="Reihenfolge" type="number" value={plan.sort_order} onChange={value => update(plan.id, 'sort_order', Number(value))} /><label className="text-xs font-black uppercase text-slate-500 md:col-span-2">Beschreibung<textarea value={plan.description} onChange={event => update(plan.id, 'description', event.target.value)} className="mt-2 min-h-20 w-full rounded-xl border px-3 py-2 text-sm font-medium normal-case" /></label></div>
                    <div className="flex flex-wrap gap-5">{([['is_active','Aktiv'],['is_public','Öffentlich sichtbar'],['is_featured','Als empfohlen markieren']] as const).map(([key,label]) => <label key={key} className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={plan[key]} onChange={event => update(plan.id, key, event.target.checked)} />{label}</label>)}</div>
                    <div><h3 className="text-sm font-black text-slate-900">Enthaltene Funktionen</h3><div className="mt-4 grid gap-5 lg:grid-cols-3">{groups.map(group => <div key={group}><p className="mb-2 text-xs font-black uppercase tracking-wide text-slate-400">{group}</p><div className="space-y-2">{PLAN_FEATURES.filter(feature => feature.group === group).map(feature => <label key={feature.id} className="flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={plan.features.includes(feature.id)} onChange={() => toggleFeature(plan, feature.id)} />{feature.label}</label>)}</div></div>)}</div></div>
                    <div className="flex justify-end"><button onClick={() => save(plan)} disabled={saving === plan.id} className="flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 text-sm font-black text-white disabled:opacity-50"><Save className="h-4 w-4" />{saving === plan.id ? 'Speichert…' : 'Paket speichern'}</button></div></div>}
            </article>)}</div></div>}
    </section>;
}

function Badge({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-indigo-50 px-2 py-1 text-[10px] font-black uppercase text-indigo-600">{children}</span>; }
function Input({ label, value, onChange, type = 'text', disabled = false }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; disabled?: boolean }) { return <label className="text-xs font-black uppercase text-slate-500">{label}<input type={type} min={type === 'number' ? 0 : undefined} step={type === 'number' ? '0.01' : undefined} value={value} disabled={disabled} onChange={event => onChange(event.target.value)} className="mt-2 block w-full rounded-xl border px-3 py-2 text-sm font-medium normal-case disabled:bg-slate-100" /></label>; }
