"use client";

import { useEffect, useState, use } from 'react';
import Link from 'next/link';
import { Activity, ArchiveRestore, ArrowLeft, Ban, Building2, CheckCircle2, CircleDollarSign, Database, FileText, HardDrive, LogOut, RefreshCw, Users } from 'lucide-react';
import { AdminNav } from '@/components/admin/AdminNav';
import { useNotification } from '@/context/NotificationContext';
import { cn } from '@/lib/utils';

interface TenantDetail {
    owner: { id: string; email: string; name: string; createdAt: string; lastSignInAt: string | null; verified: boolean };
    company: null | Record<string, string>; onboardingCompleted: boolean;
    users: Array<{ id: string; email: string; name: string; role: string; status: string; lastSignInAt: string | null }>;
    billing: null | Record<string, string | number | null>;
    access: null | { is_suspended: boolean; suspension_reason?: string; suspended_at?: string };
    usage: null | { counts: Record<string, number>; storage_bytes: number; storage_files: number; calculated_at: string; last_error?: string };
    sessions: { web: Array<{ revoked_at?: string }>; mobile: Array<{ revokedAt?: string }> };
    backups: Array<{ id: string; status: string; created_at: string; expires_at: string; file_count: number; total_bytes: number }>;
    audits: Array<{ id: number; action: string; created_at: string; details: Record<string, unknown> }>;
    documents: { invoices: number; paidRevenue: number; openAmount: number };
}

const euro = (value: number) => new Intl.NumberFormat('de-AT', { style: 'currency', currency: 'EUR' }).format(value);
const bytes = (value: number) => value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(2)} GB` : `${(value / 1024 ** 2).toFixed(1)} MB`;

export default function TenantDetailPage(props: { params: Promise<{ id: string }> }) {
    const params = use(props.params);
    const [data, setData] = useState<TenantDetail | null>(null);
    const [loading, setLoading] = useState(true);
    const { showPrompt, showConfirm, showToast } = useNotification();
    const load = async () => { setLoading(true); try { const response = await fetch(`/api/admin/tenants/${params.id}`, { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message); setData(payload); } catch (error) { showToast(error instanceof Error ? error.message : 'Firmenkonto konnte nicht geladen werden.', 'error'); } finally { setLoading(false); } };
    useEffect(() => { load(); }, [params.id]);
    if (!data) return <div className="p-10 text-sm font-bold text-slate-500">{loading ? 'Mandantenakte wird geladen…' : 'Mandantenakte nicht verfügbar.'}</div>;

    const suspended = !!data.access?.is_suspended;
    const companyName = data.company?.companyName || data.owner.name;
    const counts = data.usage?.counts || {};
    const activeSessions = data.sessions.web.filter(item => !item.revoked_at).length + data.sessions.mobile.filter(item => !item.revokedAt).length;
    const changeAccess = () => suspended ? showConfirm({ title: 'Firmenkonto entsperren', message: `${companyName} und alle Mitarbeiter erhalten wieder Zugriff.`, confirmLabel: 'Entsperren', onConfirm: async () => { const response = await fetch('/api/admin/control-center', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ companyOwnerId: data.owner.id, suspended: false }) }); if (response.ok) { showToast('Konto entsperrt.', 'success'); load(); } else showToast((await response.json()).message, 'error'); } }) : showPrompt({ title: 'Firmenkonto sperren', message: 'Der Zugriff für Eigentümer und Mitarbeiter wird vollständig blockiert. Bitte gib den Grund an.', placeholder: 'z. B. Zahlung überfällig', confirmLabel: 'Sperren', onConfirm: async reason => { if (!reason.trim()) return showToast('Sperrgrund fehlt.', 'error'); const response = await fetch('/api/admin/control-center', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ companyOwnerId: data.owner.id, suspended: true, reason: reason.trim() }) }); if (response.ok) { showToast('Konto gesperrt.', 'success'); load(); } else showToast((await response.json()).message, 'error'); } });
    const revokeAll = () => showConfirm({ title: 'Alle Sitzungen beenden', message: 'Alle Web- und Mitarbeiter-App-Sitzungen werden beendet. Das Konto bleibt aktiv.', confirmLabel: 'Alle abmelden', variant: 'danger', onConfirm: async () => { const response = await fetch('/api/admin/control-center', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'revoke_tenant_sessions', companyOwnerId: data.owner.id }) }); if (response.ok) { showToast('Alle Sitzungen beendet.', 'success'); load(); } else showToast((await response.json()).message, 'error'); } });
    const refreshUsage = async () => { const response = await fetch('/api/admin/control-center', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'refresh_usage', companyOwnerId: data.owner.id }) }); if (response.ok) { showToast('Nutzung aktualisiert.', 'success'); load(); } else showToast((await response.json()).message, 'error'); };
    const cards = [
        { label: 'Tarif', value: String(data.billing?.plan_name || 'Nicht festgelegt'), detail: `${data.billing?.payment_status || 'Zahlung unbekannt'} · ${euro(Number(data.billing?.price_amount || 0))}`, icon: CircleDollarSign },
        { label: 'Nutzer', value: data.users.length, detail: `${activeSessions} nicht widerrufene Sitzungen`, icon: Users },
        { label: 'Projekte', value: counts.projects ?? '–', detail: `${counts.customers ?? '–'} Kunden`, icon: Building2 },
        { label: 'Rechnungsumsatz', value: euro(data.documents.paidRevenue), detail: `${euro(data.documents.openAmount)} offen`, icon: FileText },
        { label: 'Storage', value: data.usage ? bytes(Number(data.usage.storage_bytes)) : '–', detail: data.usage ? `${data.usage.storage_files} Dateien` : 'Noch nicht berechnet', icon: HardDrive },
    ];

    return <div className="mx-auto max-w-[1500px] space-y-7 p-6 lg:p-10">
        <header className="space-y-5"><Link href="/admin/users" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-indigo-600"><ArrowLeft className="h-4 w-4" /> Firmen & Nutzer</Link><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-3"><h1 className="text-4xl font-black tracking-tight text-slate-950">{companyName}</h1><span className={cn('rounded-full px-3 py-1 text-xs font-black', suspended ? 'bg-rose-100 text-rose-700' : 'bg-emerald-50 text-emerald-700')}>{suspended ? 'Gesperrt' : 'Aktiv'}</span></div><p className="mt-2 text-sm font-medium text-slate-500">{data.owner.email} · <span className="font-mono">{data.owner.id}</span></p></div><div className="flex gap-2"><button onClick={revokeAll} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-bold"><LogOut className="h-4 w-4" /> Alle abmelden</button><button onClick={changeAccess} className={cn('flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-black text-white', suspended ? 'bg-emerald-600' : 'bg-rose-600')}>{suspended ? <CheckCircle2 className="h-4 w-4" /> : <Ban className="h-4 w-4" />}{suspended ? 'Entsperren' : 'Konto sperren'}</button></div></div></header>
        <AdminNav />
        {suspended && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm font-bold text-rose-800">Gesperrt: {data.access?.suspension_reason || 'Kein Grund gespeichert'}{data.access?.suspended_at ? ` · ${new Date(data.access.suspended_at).toLocaleString('de-AT')}` : ''}</div>}
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(card => <article key={card.label} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><card.icon className="h-5 w-5 text-indigo-500" /><p className="mt-4 text-xs font-black uppercase tracking-widest text-slate-400">{card.label}</p><p className="mt-2 truncate text-xl font-black text-slate-950">{card.value}</p><p className="mt-1 text-xs font-medium text-slate-500">{card.detail}</p></article>)}</section>
        <section className="grid gap-6 xl:grid-cols-2"><article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-xl font-black text-slate-950">Firma & Konto</h2><dl className="mt-6 grid gap-4 sm:grid-cols-2">{[['Kontoinhaber',data.owner.name],['E-Mail',data.company?.email || data.owner.email],['Telefon',data.company?.phone || '–'],['Adresse',[data.company?.street,data.company?.zipCode,data.company?.city].filter(Boolean).join(', ') || '–'],['Geschäftsführung',[data.company?.ceoFirstName,data.company?.ceoLastName].filter(Boolean).join(' ') || '–'],['Onboarding',data.onboardingCompleted ? 'Abgeschlossen' : 'Offen']].map(([label,value]) => <div key={label} className="rounded-2xl bg-slate-50 p-4"><dt className="text-xs font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 text-sm font-black text-slate-800">{value}</dd></div>)}</dl></article>
        <article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black text-slate-950">Nutzung</h2><p className="mt-1 text-sm text-slate-500">{data.usage ? new Date(data.usage.calculated_at).toLocaleString('de-AT') : 'Noch nicht berechnet'}</p></div><button onClick={refreshUsage} className="rounded-xl border p-3 text-slate-500"><RefreshCw className="h-4 w-4" /></button></div><div className="mt-6 grid grid-cols-3 gap-3">{[['Kunden',counts.customers],['Projekte',counts.projects],['Angebote',counts.offers],['Aufträge',counts.orders],['Rechnungen',counts.invoices],['Mitarbeiter',counts.employees],['Zeiteinträge',counts.time_entries],['Bautagebuch',counts.project_diary_entries],['Dateien',data.usage?.storage_files]].map(([label,value]) => <div key={String(label)} className="rounded-xl border p-3"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 text-lg font-black text-slate-800">{value ?? '–'}</p></div>)}</div></article></section>
        <section className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-xl font-black text-slate-950">Benutzerkonten</h2><div className="mt-5 divide-y">{data.users.map(user => <div key={user.id} className="flex items-center justify-between py-4"><div><p className="font-black text-slate-900">{user.name}</p><p className="text-xs text-slate-500">{user.email}</p></div><div className="text-right"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">{user.role}</span><p className="mt-2 text-xs text-slate-400">{user.lastSignInAt ? new Date(user.lastSignInAt).toLocaleString('de-AT') : 'Noch kein Login'}</p></div></div>)}</div></article><article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-xl font-black text-slate-950">Schnellzugriff</h2><div className="mt-5 space-y-2">{[[`/admin/billing`,'Preis & Zahlung',CircleDollarSign],[`/admin/backups`,'Backups',ArchiveRestore],[`/admin/explorer?userId=${data.owner.id}`,'Mandantendaten',Database],[`/admin/sessions`,'Sitzungen',Activity]].map(([href,label,Icon], index) => { const ItemIcon = Icon as typeof Activity; return <Link key={index} href={String(href)} className="flex items-center gap-3 rounded-xl border p-4 text-sm font-bold text-slate-700 hover:text-indigo-600"><ItemIcon className="h-4 w-4" />{String(label)}</Link>; })}</div></article></section>
        <article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-xl font-black text-slate-950">Administrative Ereignisse</h2><div className="mt-5 divide-y">{data.audits.map(event => <div key={event.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-mono text-sm font-bold text-slate-700">{event.action}</p><p className="mt-1 max-w-3xl truncate text-xs text-slate-400">{JSON.stringify(event.details)}</p></div><time className="shrink-0 text-xs font-bold text-slate-500">{new Date(event.created_at).toLocaleString('de-AT')}</time></div>)}{!data.audits.length && <p className="py-10 text-center text-sm text-slate-400">Noch keine Ereignisse.</p>}</div></article>
    </div>;
}
