"use client";
import React from "react";
import { CheckCircle2, Eye, Hash, Users2 } from "lucide-react";
import { useSubcontractorSettings } from "@/hooks/useSubcontractorSettings";

export function SubcontractorSettings({ readOnly = false }: { readOnly?: boolean }) {
    const { data, updateData, isLoading } = useSubcontractorSettings();
    if (isLoading) return <div className="p-8 font-bold text-slate-400">Laden...</div>;
    const input = "w-full rounded-2xl border border-slate-200 bg-slate-50 px-5 py-4 font-medium text-slate-800 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20";
    const number = String(Math.max(1, Number(data.nextNumber) || 1));
    const preview = `${data.prefix || ""}${"0".repeat(Math.max(0, (data.mindestLaenge || 1) - number.length))}${number}`;
    const descriptionNumber = String(Math.max(1, Number(data.descriptionNextNumber) || 1));
    const descriptionPreview = `${data.descriptionPrefix || "LB-"}${new Date().getFullYear()}-${"0".repeat(Math.max(0, (data.descriptionPadding || 1) - descriptionNumber.length))}${descriptionNumber}`;
    const change = (name: string, value: string) => updateData({ [name]: ["nextNumber", "mindestLaenge", "descriptionNextNumber", "descriptionPadding"].includes(name) ? Math.max(1, Number(value) || 1) : value });
    const Preview = ({ value, color }: { value: string; color: string }) => <div className="mx-8 mb-8 flex items-center gap-4 rounded-3xl border border-slate-200 bg-slate-50 p-6"><Eye className={color} /><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Vorschau nächste Nummer</p><p className={`text-xl font-black ${color.replace("text-", "text-")}`}>{value}</p></div></div>;
    return <div className="mx-auto max-w-5xl space-y-6"><div className="flex items-center gap-4 rounded-3xl border border-indigo-100/50 bg-indigo-50/50 p-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-600"><Users2 className="text-white" /></div><h2 className="text-3xl font-black text-slate-900">Subunternehmer & Leistungsbeschreibungen</h2></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-6"><Hash className="text-indigo-600" /><h3 className="text-xl font-bold">Subunternehmer-Nummernkreis</h3></div><div className="grid gap-8 p-8 md:grid-cols-3"><label className="space-y-2 text-sm font-bold">Präfix<input className={input} value={data.prefix} disabled={readOnly} onChange={e => change("prefix", e.target.value)} /></label><label className="space-y-2 text-sm font-bold">Nächste Subunternehmernummer<input className={input} type="number" min={1} value={data.nextNumber} disabled={readOnly} onChange={e => change("nextNumber", e.target.value)} /></label><label className="space-y-2 text-sm font-bold">Mindeststellen (Padding)<input className={input} type="number" min={1} max={10} value={data.mindestLaenge} disabled={readOnly} onChange={e => change("mindestLaenge", e.target.value)} /></label></div><Preview value={preview} color="text-indigo-600" /></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-6"><Hash className="text-violet-600" /><h3 className="text-xl font-bold">Leistungsbeschreibungs-Nummernkreis</h3></div><div className="grid gap-8 p-8 md:grid-cols-3"><label className="space-y-2 text-sm font-bold">Präfix<input className={input} value={data.descriptionPrefix} disabled={readOnly} onChange={e => change("descriptionPrefix", e.target.value)} /></label><label className="space-y-2 text-sm font-bold">Nächste Nummer<input className={input} type="number" min={1} value={data.descriptionNextNumber} disabled={readOnly} onChange={e => change("descriptionNextNumber", e.target.value)} /></label><label className="space-y-2 text-sm font-bold">Mindeststellen (Padding)<input className={input} type="number" min={1} max={10} value={data.descriptionPadding} disabled={readOnly} onChange={e => change("descriptionPadding", e.target.value)} /></label></div><Preview value={descriptionPreview} color="text-violet-600" /></div>{!readOnly && <div className="flex justify-end rounded-3xl border border-emerald-100 bg-emerald-50 p-6"><span className="flex items-center gap-2 font-black text-emerald-600"><CheckCircle2 className="h-5 w-5" />Automatisch gespeichert</span></div>}</div>;
}
